# Generated by Django 4.2.9 on 2024-02-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='N/A', null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='IMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=1000)),
                ('last_name', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('usertype', models.CharField(choices=[('eit', 'Eit'), ('teaching_fellow', 'Teaching Fellow'), ('admin_staff', 'Admin Staff'), ('admin', 'Admin')], default='eit', max_length=1000)),
                ('description', models.TextField(blank=True, default='N/A', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortmembers_author', to='users.imuser')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.cohort')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortmembers_member', to='users.imuser')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_cohorts_author', to='users.imuser'),
        ),
    ]
